package com.example.hungry.login.model;

public class User {

    int CM_ID,CM_MA_ID,COUNTRY_COUNTRY_MASTRE_ID,STATE_MASTER_ID,CITY_MASTER_ID;

    String CM_FIRST_NAME,CM_LAST_NAME,CM_MOBILE,CM_EMAIL,CM_IPADDRESS,CM_PASSWORD,CM_IS_MOBILE_VERIFIED,CM_IS_AGREE,CM_ADDRESS,CM_ACTIVE,CM_IS_EMAIL_VERIFIEDCM_LOGIN_ATTEMPT_NO,CM_DOB,CM_GENDER,CM_REG_SOURCE,CM_PRO_IMG,CM_CREATED_AT,CM_UPDATED_AT,CM_TOKEN_SATUS_DATE,CM_TOKEN_SATU;


}
